import { copyFileSync, existsSync, mkdirSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { SELECTABLE_MODELS, TOGETHER_BASE_URL, VISION_PRIMARY } from "@togetherlink/models";
import type { ModelDefinition } from "@togetherlink/models";

export const GROK_API_KEY_ENV = "TOGETHER_API_KEY";
export const GROK_MAX_COMPLETION_TOKENS = 8192;
export const GROK_IDENTITY_RULE =
  "Grok Build is only the terminal harness. You are the selected Together AI model via togetherlink, not Grok or an xAI model. For identity questions, name the selected backend and Together AI; never claim xAI built or serves you.";

const GROK_PERSISTENT_DIRECTORIES = [
  "sessions",
  "memory",
  "skills",
  "plugins",
  "agents",
  "installed-plugins",
  "marketplace-cache",
  "projects",
] as const;

const GROK_PERSISTENT_FILES = ["pager.toml", "lsp.json", "mcp_credentials.json", "worktrees.db"];

export function grokModelAlias(model: ModelDefinition): string {
  const slug = model.id
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, "-")
    .replaceAll(/^-|-$/g, "");
  return `together-${slug}`;
}

export const GROK_VISION_MODEL_ALIAS = grokModelAlias(VISION_PRIMARY);

export function buildGrokIdentityRule(model: ModelDefinition): string {
  return `Grok Build is only the terminal harness. You are ${model.name} (${model.id}), served by Together AI via togetherlink. You are not Grok or an xAI model. For identity questions, name this backend and Together AI; never claim xAI built or serves you.`;
}

export function buildGrokConfigToml(
  selectedModel: ModelDefinition,
  baseUrl = TOGETHER_BASE_URL,
): string {
  const selectedAlias = grokModelAlias(selectedModel);
  const lines = [
    "# Generated by togetherlink for this Grok launch. The Together key stays in the environment.",
    "[cli]",
    "auto_update = false",
    "",
    "[models]",
    `default = ${tomlString(selectedAlias)}`,
    `session_summary = ${tomlString(selectedAlias)}`,
    `image_description = ${tomlString(GROK_VISION_MODEL_ALIAS)}`,
    "",
    "[features]",
    "telemetry = false",
    "feedback = false",
  ];

  for (const model of SELECTABLE_MODELS) {
    const alias = grokModelAlias(model);
    lines.push(
      "",
      `[model.${alias}]`,
      `model = ${tomlString(model.id)}`,
      `base_url = ${tomlString(baseUrl)}`,
      `name = ${tomlString(`Together AI · ${model.name}`)}`,
      `description = ${tomlString(`Direct Together API model: ${model.id}`)}`,
      `env_key = ${tomlString(GROK_API_KEY_ENV)}`,
      'api_backend = "chat_completions"',
      `context_window = ${model.limit.context}`,
      `max_completion_tokens = ${Math.min(model.limit.output, GROK_MAX_COMPLETION_TOKENS)}`,
    );
  }

  return `${lines.join("\n")}\n`;
}

/**
 * Grok only accepts its main model catalog through $GROK_HOME/config.toml.
 * Use an isolated home, snapshot the user's non-model config as a lower-priority
 * managed layer, and link user state that should survive a launch. The user's
 * real config.toml and authentication files are never modified or exposed.
 */
export function populateTemporaryGrokHome({
  temporaryHome,
  persistentHome,
  selectedModel,
  baseUrl = TOGETHER_BASE_URL,
}: {
  temporaryHome: string;
  persistentHome: string;
  selectedModel: ModelDefinition;
  baseUrl?: string;
}): void {
  mkdirSync(temporaryHome, { recursive: true });
  mkdirSync(persistentHome, { recursive: true });

  const userConfig = join(persistentHome, "config.toml");
  if (existsSync(userConfig)) {
    copyFileSync(userConfig, join(temporaryHome, "managed_config.toml"));
  }

  writeFileSync(
    join(temporaryHome, "config.toml"),
    buildGrokConfigToml(selectedModel, baseUrl),
    "utf8",
  );

  const sessions = join(persistentHome, "sessions");
  mkdirSync(sessions, { recursive: true });
  linkDirectory(sessions, join(temporaryHome, "sessions"));

  for (const name of GROK_PERSISTENT_DIRECTORIES) {
    if (name === "sessions") continue;
    const source = join(persistentHome, name);
    if (existsSync(source)) linkDirectory(source, join(temporaryHome, name));
  }

  for (const name of GROK_PERSISTENT_FILES) {
    const source = join(persistentHome, name);
    if (existsSync(source)) copyFileSync(source, join(temporaryHome, name));
  }
}

export function grokArgsWithoutTogetherlinkOverrides(args: string[]): string[] {
  const sanitized: string[] = [];
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === undefined) continue;
    if (arg === "--model" || arg === "-m") {
      index += 1;
      continue;
    }
    if (arg.startsWith("--model=") || (arg.startsWith("-m") && arg.length > 2)) continue;
    sanitized.push(arg);
  }
  return sanitized;
}

export function grokArgsWithTogetherlinkIdentity(
  args: string[],
  identityRule = GROK_IDENTITY_RULE,
): string[] {
  const sanitized = grokArgsWithoutTogetherlinkOverrides(args);
  const passthrough: string[] = [];
  const userRules: string[] = [];
  let systemPromptOverride: string | undefined;

  for (let index = 0; index < sanitized.length; index += 1) {
    const arg = sanitized[index];
    if (arg === undefined) continue;

    if (arg === "--disable-web-search") {
      continue;
    }

    if (arg === "--rules" || arg === "--append-system-prompt") {
      const value = sanitized[index + 1];
      if (value !== undefined) {
        userRules.push(value);
        index += 1;
      }
      continue;
    }
    if (arg.startsWith("--rules=") || arg.startsWith("--append-system-prompt=")) {
      userRules.push(arg.slice(arg.indexOf("=") + 1));
      continue;
    }

    if (arg === "--system-prompt-override" || arg === "--system-prompt") {
      const value = sanitized[index + 1];
      if (value !== undefined) {
        systemPromptOverride = value;
        index += 1;
      }
      continue;
    }
    if (arg.startsWith("--system-prompt-override=") || arg.startsWith("--system-prompt=")) {
      systemPromptOverride = arg.slice(arg.indexOf("=") + 1);
      continue;
    }

    passthrough.push(arg);
  }

  if (systemPromptOverride !== undefined) {
    return [
      "--disable-web-search",
      `--system-prompt-override=${joinPromptRules(systemPromptOverride, identityRule)}`,
      ...passthrough,
    ];
  }

  return [
    "--disable-web-search",
    "--rules",
    joinPromptRules(identityRule, ...userRules),
    ...passthrough,
  ];
}

function linkDirectory(source: string, destination: string): void {
  symlinkSync(source, destination, process.platform === "win32" ? "junction" : undefined);
}

function joinPromptRules(...rules: string[]): string {
  return rules.filter((rule) => rule.trim().length > 0).join("\n\n");
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}
