import { createHash } from "node:crypto";
import { mkdir, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import type { ModelDefinition } from "@togetherlink/models";
import { CODEX_SUPPORTED_MODELS, type CodexModelSelection } from "../codex/defaults.js";
import { TOGETHER_BASE_URL } from "../together-core.js";

export const PRIME_PROVIDER_ID = "togetherlink";
export const PRIME_API_KEY_ENV = "TOGETHER_API_KEY";

type PrimeThinkingLevel = "minimal" | "low" | "medium" | "high" | "xhigh";

export type PrimeProviderConfig = {
  name: string;
  baseUrl: string;
  apiKey: string;
  api: "openai-completions";
  models: Array<{
    id: string;
    name: string;
    reasoning: boolean;
    input: Array<"text" | "image">;
    contextWindow: number;
    maxTokens: number;
    cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
    thinkingLevelMap?: Partial<Record<PrimeThinkingLevel, string | null>>;
  }>;
};

export type PrimeLaunchSpec = {
  binary: "prime-agent";
  args: string[];
  env: NodeJS.ProcessEnv;
};

const VALUE_FLAGS = new Set(["--api-key", "--model", "--models", "--provider"]);

function primeModelInput(model: ModelDefinition): Array<"text" | "image"> {
  const input: Array<"text" | "image"> = ["text"];
  if (model.attachment && model.modalities.input.includes("image")) {
    input.push("image");
  }
  return input;
}

function primeThinkingLevelMap(
  model: ModelDefinition,
): Partial<Record<PrimeThinkingLevel, string | null>> | undefined {
  if (!model.reasoningEfforts) {
    return undefined;
  }
  const supported = new Set(model.reasoningEfforts);
  return {
    minimal: null,
    low: supported.has("low") ? "low" : null,
    medium: supported.has("medium") ? "medium" : null,
    high: supported.has("high") ? "high" : null,
    xhigh: supported.has("max") ? "max" : null,
  };
}

export function buildPrimeProviderConfig(baseUrl = TOGETHER_BASE_URL): PrimeProviderConfig {
  return {
    name: "Together AI via TogetherLink",
    baseUrl,
    // Prime resolves this name only when no runtime --api-key override exists.
    // TogetherLink always supplies the actual key at runtime, never in this file.
    apiKey: PRIME_API_KEY_ENV,
    api: "openai-completions",
    models: CODEX_SUPPORTED_MODELS.map(({ definition }) => {
      const thinkingLevelMap = primeThinkingLevelMap(definition);
      return {
        id: definition.id,
        name: `Together AI · ${definition.name}`,
        reasoning: definition.reasoning,
        input: primeModelInput(definition),
        contextWindow: definition.limit.context,
        maxTokens: definition.limit.output,
        cost: {
          input: definition.cost.input,
          output: definition.cost.output,
          cacheRead: definition.cost.cache_read,
          cacheWrite: 0,
        },
        ...(thinkingLevelMap ? { thinkingLevelMap } : {}),
      };
    }),
  };
}

export function buildPrimeProviderExtensionSource(baseUrl = TOGETHER_BASE_URL): string {
  const config = JSON.stringify(buildPrimeProviderConfig(baseUrl), null, 2);
  return `// Generated by TogetherLink. Contains model metadata only; no credentials.\nexport default function registerTogetherLinkProvider(pi) {\n  pi.registerProvider(${JSON.stringify(PRIME_PROVIDER_ID)}, ${config});\n}\n`;
}

export function resolvePrimeProviderExtensionPath(
  home: string,
  baseUrl = TOGETHER_BASE_URL,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const togetherlinkRoot = env.TOGETHERLINK_HOME?.trim() || join(home, ".togetherlink");
  const endpointHash = createHash("sha256").update(baseUrl).digest("hex").slice(0, 12);
  return join(togetherlinkRoot, "prime-agent", `together-provider-${endpointHash}.js`);
}

export async function writePrimeProviderExtension(
  filePath: string,
  baseUrl = TOGETHER_BASE_URL,
): Promise<void> {
  // The activation is ephemeral (--extension), but the metadata file stays in
  // TogetherLink's own home so a detached Prime worker can recover after the
  // launcher exits. It contains no credential and never changes Prime's home.
  await mkdir(dirname(filePath), { recursive: true });
  const temporaryPath = `${filePath}.tmp-${process.pid}`;
  await writeFile(temporaryPath, buildPrimeProviderExtensionSource(baseUrl), { mode: 0o600 });
  await rename(temporaryPath, filePath);
}

export function primeArgsWithoutTogetherlinkOverrides(args: string[]): string[] {
  const sanitized: string[] = [];
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === undefined) {
      continue;
    }
    if (arg === "--") {
      sanitized.push(...args.slice(index));
      break;
    }
    if (VALUE_FLAGS.has(arg)) {
      index += 1;
      continue;
    }
    if (
      arg.startsWith("--api-key=") ||
      arg.startsWith("--model=") ||
      arg.startsWith("--models=") ||
      arg.startsWith("--provider=")
    ) {
      continue;
    }
    sanitized.push(arg);
  }
  return sanitized;
}

export function buildPrimeLaunchSpec({
  selectedModel,
  apiKey,
  baseUrl,
  extensionPath,
  passthrough,
  env = process.env,
}: {
  selectedModel: CodexModelSelection;
  apiKey: string;
  baseUrl: string;
  extensionPath: string;
  passthrough: string[];
  env?: NodeJS.ProcessEnv;
}): PrimeLaunchSpec {
  const models = CODEX_SUPPORTED_MODELS.map(({ id }) => `${PRIME_PROVIDER_ID}/${id}`).join(",");
  return {
    binary: "prime-agent",
    args: [
      "--extension",
      extensionPath,
      "--provider",
      PRIME_PROVIDER_ID,
      "--model",
      selectedModel.id,
      "--models",
      models,
      "--api-key",
      apiKey,
      ...primeArgsWithoutTogetherlinkOverrides(passthrough),
    ],
    env: {
      ...env,
      TOGETHER_API_KEY: apiKey,
      TOGETHER_BASE_URL: baseUrl,
    },
  };
}
