import { createHash, randomUUID } from "node:crypto";
import { mkdir, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { stringify } from "yaml";
import type { ModelDefinition, ModelReasoningEffort } from "@togetherlink/models";
import { CODEX_SUPPORTED_MODELS, type CodexModelSelection } from "../codex/defaults.js";
import { TOGETHER_BASE_URL } from "../together-core.js";

export const DEEPSEEK_PROVIDER_ID = "togetherlink";
export const DEEPSEEK_API_KEY_ENV = "TOGETHER_API_KEY";
export const NATIVE_DEEPSEEK_API_KEY_ENV = "DEEPSEEK_API_KEY";

type DeepseekModel = {
  id: string;
  name: string;
  contextWindow: number;
  maxTokens: number;
  input: Array<"text" | "image">;
  reasoningEfforts?: Partial<Record<ModelReasoningEffort, string>>;
};

export type DeepseekPatch = [
  {
    id: "llm-pi-ai";
    config: {
      providers: {
        togetherlink: {
          displayName: string;
          apiKeyEnv: typeof DEEPSEEK_API_KEY_ENV;
          api: "openai-completions";
          baseURL: string;
          compat: { thinkingFormat: "together"; supportsReasoningEffort: true };
          models: DeepseekModel[];
        };
      };
    };
  },
  {
    id: "agent-default-model";
    config: { provider: typeof DEEPSEEK_PROVIDER_ID; model: string };
  },
  { id: "llm-deepseek"; disabled: true }?,
];

export type DeepseekLaunchSpec = {
  binary: "dsh";
  args: string[];
  env: NodeJS.ProcessEnv;
};

function modelInput(model: ModelDefinition): Array<"text" | "image"> {
  return model.attachment && model.modalities.input.includes("image")
    ? ["text", "image"]
    : ["text"];
}

function reasoningEfforts(
  model: ModelDefinition,
): Partial<Record<ModelReasoningEffort, string>> | undefined {
  if (!model.reasoningEfforts || model.reasoningEfforts.length === 0) {
    return undefined;
  }
  return Object.fromEntries(model.reasoningEfforts.map((effort) => [effort, effort]));
}

export function buildDeepseekPatch(
  selectedModel: CodexModelSelection,
  baseUrl = TOGETHER_BASE_URL,
  nativeDeepseekApiKey = process.env[NATIVE_DEEPSEEK_API_KEY_ENV],
): DeepseekPatch {
  const patch: DeepseekPatch = [
    {
      id: "llm-pi-ai",
      config: {
        providers: {
          togetherlink: {
            displayName: "Together AI via TogetherLink",
            apiKeyEnv: DEEPSEEK_API_KEY_ENV,
            api: "openai-completions",
            baseURL: baseUrl,
            compat: { thinkingFormat: "together", supportsReasoningEffort: true },
            models: CODEX_SUPPORTED_MODELS.map(({ definition }) => {
              const efforts = reasoningEfforts(definition);
              return {
                id: definition.id,
                name: definition.name,
                contextWindow: definition.limit.context,
                maxTokens: definition.limit.output,
                input: modelInput(definition),
                ...(efforts ? { reasoningEfforts: efforts } : {}),
              };
            }),
          },
        },
      },
    },
    {
      id: "agent-default-model",
      config: { provider: DEEPSEEK_PROVIDER_ID, model: selectedModel.id },
    },
  ];

  if (!nativeDeepseekApiKey?.trim()) {
    patch.push({ id: "llm-deepseek", disabled: true });
  }

  return patch;
}

export function buildDeepseekPatchSource(
  selectedModel: CodexModelSelection,
  baseUrl = TOGETHER_BASE_URL,
  nativeDeepseekApiKey = process.env[NATIVE_DEEPSEEK_API_KEY_ENV],
): string {
  return `# Generated by TogetherLink. Contains model metadata only; no credentials.\n${stringify(
    buildDeepseekPatch(selectedModel, baseUrl, nativeDeepseekApiKey),
  )}`;
}

export function resolveDeepseekPatchPath(
  home: string,
  selectedModel: CodexModelSelection,
  baseUrl = TOGETHER_BASE_URL,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const togetherlinkRoot = env.TOGETHERLINK_HOME?.trim() || join(home, ".togetherlink");
  const contentHash = createHash("sha256")
    .update(buildDeepseekPatchSource(selectedModel, baseUrl, env[NATIVE_DEEPSEEK_API_KEY_ENV]))
    .digest("hex")
    .slice(0, 12);
  return join(togetherlinkRoot, "deepseek-harness", `together-provider-${contentHash}.cordis.yml`);
}

export async function writeDeepseekPatch(
  filePath: string,
  selectedModel: CodexModelSelection,
  baseUrl = TOGETHER_BASE_URL,
  nativeDeepseekApiKey = process.env[NATIVE_DEEPSEEK_API_KEY_ENV],
): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true });
  const temporaryPath = `${filePath}.tmp-${process.pid}-${randomUUID()}`;
  await writeFile(
    temporaryPath,
    buildDeepseekPatchSource(selectedModel, baseUrl, nativeDeepseekApiKey),
    { mode: 0o600 },
  );
  await rename(temporaryPath, filePath);
}

function argsWithoutPatchOverrides(args: string[]): string[] {
  const sanitized: string[] = [];
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--patch") {
      index += 1;
      continue;
    }
    if (arg?.startsWith("--patch=")) {
      continue;
    }
    if (arg !== undefined) {
      sanitized.push(arg);
    }
  }
  return sanitized;
}

export function buildDeepseekLaunchSpec({
  apiKey,
  baseUrl,
  patchPath,
  passthrough,
  env = process.env,
}: {
  apiKey: string;
  baseUrl: string;
  patchPath: string;
  passthrough: string[];
  env?: NodeJS.ProcessEnv;
}): DeepseekLaunchSpec {
  return {
    binary: "dsh",
    args: ["web", "--patch", patchPath, ...argsWithoutPatchOverrides(passthrough)],
    env: {
      ...env,
      TOGETHER_API_KEY: apiKey,
      TOGETHER_BASE_URL: baseUrl,
    },
  };
}
