import {
  existsSync,
  copyFileSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { isMap, parseDocument } from "yaml";

export type HermesLaunchMode = "terminal" | "desktop";

export type HermesLaunchSpec = {
  binary: "hermes";
  args: string[];
  env: NodeJS.ProcessEnv;
};

type BuildHermesLaunchSpecOptions = {
  mode: HermesLaunchMode;
  modelId: string;
  apiKey: string;
  baseUrl: string;
  hermesHome: string;
  passthrough?: string[];
  env?: NodeJS.ProcessEnv;
};

type HermesHomeOverlayOptions = {
  baseUrl: string;
  modelIds: readonly string[];
};

const VALUE_OVERRIDES = new Set(["--provider", "--model", "-m"]);
const ISOLATED_HOME_ENTRIES = new Set([".env", "active_profile"]);
const HERMES_PROVIDER_ID = "togetherlink";
const HERMES_PROVIDER_API_KEY_ENV = "TOGETHERLINK_HERMES_API_KEY";
const HERMES_PROVIDER_BASE_URL_ENV = "TOGETHERLINK_HERMES_BASE_URL";

export function resolveHermesCommand(args: string[]): {
  mode: HermesLaunchMode;
  passthrough: string[];
} {
  return args[0] === "desktop"
    ? { mode: "desktop", passthrough: args.slice(1) }
    : { mode: "terminal", passthrough: args };
}

function containsCredentialState(name: string): boolean {
  return ISOLATED_HOME_ENTRIES.has(name) || /auth|credential|token/i.test(name);
}

function linkDirectoryEntries(
  source: string,
  destination: string,
  excludedNames: ReadonlySet<string> = new Set(),
): void {
  if (!existsSync(source)) {
    return;
  }
  mkdirSync(destination, { recursive: true });
  for (const entry of readdirSync(source, { withFileTypes: true })) {
    if (excludedNames.has(entry.name)) {
      continue;
    }
    symlinkSync(
      join(source, entry.name),
      join(destination, entry.name),
      entry.isDirectory() ? "dir" : "file",
    );
  }
}

function writeTogetherProviderPlugin(
  overlay: string,
  { baseUrl, modelIds }: HermesHomeOverlayOptions,
): void {
  const pluginDir = join(overlay, "plugins", "model-providers", HERMES_PROVIDER_ID);
  mkdirSync(pluginDir, { recursive: true });
  const modelValues = modelIds.map((modelId) => JSON.stringify(modelId)).join(", ");
  const pythonTuple = modelIds.length === 1 ? `${modelValues},` : modelValues;
  writeFileSync(
    join(pluginDir, "__init__.py"),
    `"""Ephemeral Together AI provider generated by togetherlink."""

from providers import register_provider
from providers.base import ProviderProfile


class TogetherLinkProfile(ProviderProfile):
    def prepare_messages(self, messages):
        prepared = []
        for message in messages:
            item = dict(message)
            if item.get("role") == "tool":
                item.pop("name", None)
            prepared.append(item)
        return prepared


togetherlink = TogetherLinkProfile(
    name="togetherlink",
    display_name="Together AI",
    description="Together AI through togetherlink",
    api_mode="chat_completions",
    env_vars=("${HERMES_PROVIDER_API_KEY_ENV}", "${HERMES_PROVIDER_BASE_URL_ENV}"),
    base_url=${JSON.stringify(baseUrl)},
    fallback_models=(${pythonTuple}),
    supports_vision=True,
)

register_provider(togetherlink)
`,
    "utf8",
  );
  writeFileSync(
    join(pluginDir, "plugin.yaml"),
    `name: togetherlink
kind: model-provider
version: 1.0.0
description: Ephemeral Together AI provider generated by togetherlink
`,
    "utf8",
  );
}

function writeTogetherProviderConfig(
  overlay: string,
  { baseUrl, modelIds }: HermesHomeOverlayOptions,
): void {
  const configPath = join(overlay, "config.yaml");
  const source = existsSync(configPath) ? readFileSync(configPath, "utf8") : "";
  const document = parseDocument(source);
  if (document.errors.length > 0) {
    throw new Error(`Cannot prepare temporary Hermes config: ${document.errors[0]?.message}`);
  }

  if (!isMap(document.get("providers", true))) {
    document.set("providers", document.createNode({}));
  }
  document.setIn(["providers", HERMES_PROVIDER_ID], {
    name: "Together AI",
    base_url: baseUrl,
    key_env: HERMES_PROVIDER_API_KEY_ENV,
    transport: "chat_completions",
    default_model: modelIds[0] ?? "",
    models: [...modelIds],
    discover_models: false,
  });
  writeFileSync(configPath, document.toString(), "utf8");
}

/**
 * Give each TogetherLink launch an isolated root while mirroring ordinary
 * Hermes state so sessions, skills, memories, and user preferences remain
 * native and resumable. Credential files stay excluded; the Together key is
 * supplied only in the child process environment. The provider plugin exists
 * only in this overlay.
 */
export function createHermesHomeOverlay(
  nativeHome: string,
  options: HermesHomeOverlayOptions,
): string {
  const overlay = mkdtempSync(join(tmpdir(), "togetherlink-hermes-"));
  try {
    if (existsSync(nativeHome)) {
      for (const entry of readdirSync(nativeHome, { withFileTypes: true })) {
        if (containsCredentialState(entry.name) || entry.name === "plugins") {
          continue;
        }
        if (entry.name === "config.yaml" && entry.isFile()) {
          copyFileSync(join(nativeHome, entry.name), join(overlay, entry.name));
          continue;
        }
        symlinkSync(
          join(nativeHome, entry.name),
          join(overlay, entry.name),
          entry.isDirectory() ? "dir" : "file",
        );
      }

      const nativePlugins = join(nativeHome, "plugins");
      const overlayPlugins = join(overlay, "plugins");
      if (existsSync(nativePlugins)) {
        mkdirSync(overlayPlugins, { recursive: true });
        for (const entry of readdirSync(nativePlugins, { withFileTypes: true })) {
          if (entry.name === "model-providers") {
            continue;
          }
          symlinkSync(
            join(nativePlugins, entry.name),
            join(overlayPlugins, entry.name),
            entry.isDirectory() ? "dir" : "file",
          );
        }
        linkDirectoryEntries(
          join(nativePlugins, "model-providers"),
          join(overlayPlugins, "model-providers"),
          new Set([HERMES_PROVIDER_ID]),
        );
      }
    }
    writeTogetherProviderConfig(overlay, options);
    writeTogetherProviderPlugin(overlay, options);
    return overlay;
  } catch (error) {
    rmSync(overlay, { recursive: true, force: true });
    throw error;
  }
}

function argsWithoutRuntimeOverrides(args: string[]): string[] {
  const sanitized: string[] = [];
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg === undefined) {
      continue;
    }
    if (VALUE_OVERRIDES.has(arg)) {
      i += 1;
      continue;
    }
    if (arg.startsWith("--provider=") || arg.startsWith("--model=")) {
      continue;
    }
    sanitized.push(arg);
  }
  return sanitized;
}

/** Build the complete, process-local Hermes runtime. */
export function buildHermesLaunchSpec({
  mode,
  modelId,
  apiKey,
  baseUrl,
  hermesHome,
  passthrough = [],
  env = process.env,
}: BuildHermesLaunchSpecOptions): HermesLaunchSpec {
  const forwardedArgs = argsWithoutRuntimeOverrides(passthrough);
  return {
    binary: "hermes",
    args:
      mode === "desktop"
        ? ["desktop", ...forwardedArgs]
        : ["--provider", HERMES_PROVIDER_ID, "--model", modelId, ...forwardedArgs],
    env: {
      ...env,
      TOGETHER_API_KEY: apiKey,
      TOGETHER_BASE_URL: baseUrl,
      [HERMES_PROVIDER_API_KEY_ENV]: apiKey,
      [HERMES_PROVIDER_BASE_URL_ENV]: baseUrl,
      HERMES_HOME: hermesHome,
      HERMES_MODEL: modelId,
      HERMES_INFERENCE_MODEL: modelId,
      HERMES_INFERENCE_PROVIDER: HERMES_PROVIDER_ID,
      HERMES_TUI_PROVIDER: HERMES_PROVIDER_ID,
    },
  };
}
